apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docwhat-blog
  namespace: argocd
spec:
  destination:
    namespace: docwhat
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: docwhat-manifests
    repoURL: git@github.com:holtje/hive-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
