apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "metrics-server"
  namespace: "argocd"
spec:
  project: "system"
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: "metrics-server"
    targetRevision: "4.*"
    helm:
      values: |
        ---
        apiService:
          create: true
        extraArgs:
          kubelet-insecure-tls: true
          kubelet-preferred-address-types: "InternalIP"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "kube-system"
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
