apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: system

  source:
    chart: sealed-secrets
    helm:
      parameters:
        - name: namespace
          value: kube-system
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: "1.13.2"

  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      selfHeal: true
      prune: false
