---
apiVersion: v1
kind: Service
metadata:
  annotations:
    ignore-check.kube-linter.io/dangling-service: Linter is incorrectly detecting a problem.
  name: traefik-metrics
  namespace: traefik
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik-metrics
spec:
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  ports:
    - name: metrics
      port: 8082
      targetPort: 8082
  type: ClusterIP
