---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: e1b1cc32e02deb06426e
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: holtje
  repositories: |
    - name: bitnami
      type: helm
      url: https://charts.bitnami.com/bitnami
    - name: prometheus-community
      type: helm
      url: https://prometheus-community.github.io/helm-charts
    - name: sealed-secrets
      type: helm
      url: https://bitnami-labs.github.io/sealed-secrets
    - name: argo-helm
      type: helm
      url: https://argoproj.github.io/argo-helm
    - type: git
      url: git@github.com:holtje/hive-config.git
      sshPrivateKeySecret:
        name: argocd-secret
        key: github.holtje.hive-config
  statusbadge.enabled: "true"
  url: https://argocd.docwhat.net
  resource.customizations: |
    bitnami.com/SealedSecret:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Controller doesn't report resource status"
        return hs
