---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
    sealedsecrets.bitnami.com/managed: 'true'
type: Opaque
