---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-production
  namespace: docwhat
  annotations:
    ignore-check.kube-linter.io/run-as-non-root: "TODO: this doesn't need to run as\
      \ root."
    ignore-check.kube-linter.io/unset-memory-requirements: 'TODO: this should work
      better now.'
    ignore-check.kube-linter.io/unset-cpu-requirements: What is a good max CPU?
spec:
  selector:
    matchLabels:
      app: blog
      environment: production
  template:
    metadata:
      labels:
        environment: production
        app: blog
    spec:
      containers:
        - name: blog
          image: ghcr.io/docwhat/blog:sha-ae98f4b5
          resources:
            requests:
              memory: 8Mi
            limits:
              memory: 32Mi
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache-volume
            - mountPath: /run
              name: run-volume
          securityContext:
            readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: github-docker-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blog-production
  namespace: docwhat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-production
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-production
  namespace: docwhat
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: blog
    environment: production
