#!/bin/bash

set -euo pipefail

typeset -ra programs=(
  argocd
  fluxctl
  helm
  jq
  kubectl
  kubeseal
  kustomize
  octant
)

typeset -r is_macos=$(if [[ $OSTYPE == darwin* ]]; then echo 1; else echo 0; fi)

has() {
  command -v "$1" >/dev/null 2>&1
}

typeset -a missing=()
for program in "${programs[@]}"; do
  if ! has "$program"; then
    missing+=("$program")
  fi
done

if (("${#missing[@]}")) && ((is_macos)) && has brew; then
  brew install "${missing[@]}"
  missing=()
fi

if ((is_macos)); then
  if [[ -x /usr/local/bin/pip3 ]]; then
    /usr/local/bin/pip3 install linode-cli --upgrade --quiet
  else
    /usr/bin/pip3 install linode-cli --upgrade --quiet --user
  fi
else
  missing+=(python3)
fi

if (("${#missing[@]}")); then
  echo "Please install the following programs:"
  for program in "${programs[@]}"; do
    echo " - ${program}"
  done
else
  echo "You are bootstrapped and ready to go! "
fi

# EOF
