#!/bin/bash

set -euo pipefail

typeset -ra programs=(
  argocd
  gh
  helm
  jq
  kubectl
  kubeseal
  kustomize
  octant
  yq
)

is_macos=$(if [[ ${OSTYPE} == darwin* ]]; then echo 1; else echo 0; fi)
readonly is_macos

has() {
  command -v "$1" >/dev/null 2>&1
}

typeset -a missing=()
for program in "${programs[@]}"; do
  if ! has "${program}"; then
    missing+=("${program}")
  fi
done

if (("${#missing[@]}")) && ((is_macos)) && has brew; then
  brew install "${missing[@]}"
  missing=()
fi

if ((is_macos)); then
  if has brew; then
    "$(brew --prefix)/bin/pip" install linode-cli --upgrade --quiet
  elif has pip3; then
    pip3 install linode-cli --upgrade --quiet --user
  else
    pip install linode-cli --upgrade --quiet --user
  fi
else
  missing+=(python3)
fi

if (("${#missing[@]}")); then
  echo "Please install the following programs:"
  for program in "${programs[@]}"; do
    echo " - ${program}"
  done
else
  echo "You are bootstrapped and ready to go! "
fi

# EOF
