#!/bin/bash

set -euo pipefail

exec helm upgrade -i \
  helm-operator \
  fluxcd/helm-operator \
  "--set=git.ssh.secretName=flux-git-deploy" \
  "--set=helm.versions=v3" \
  "--namespace=flux"

# EOF
