apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.0.4

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
  - ./resources/argocd-sealedsecret.yaml
  - ./resources/cluster-hive-secret.yaml
  - ./resources/default-project.yaml
  - ./resources/system-project.yaml
  - ./resources/ingress-route.yaml

# Each entry in this list should resolve to
# a kubernetes object and a JSON patch that will be applied
# to the object.
# The JSON patch is documented at https://tools.ietf.org/html/rfc6902
#
# target field points to a kubernetes object within the same kustomization
# by the object's group, version, kind, name and namespace.
# path field is a relative file path of a JSON patch file.
# The content in this patch file can be either in JSON format as
#
#  [
#    {"op": "add", "path": "/some/new/path", "value": "value"},
#    {"op": "replace", "path": "/some/existing/path", "value": "new value"}
#  ]
#
# or in YAML format as
#
# - op: add
#   path: /some/new/path
#   value: value
# - op:replace
#   path: /some/existing/path
#   value: new value
#
patchesJson6902:
  - path: ./overlays/argocd-application-controller-statefulset-patch.json
    target:
      group: apps
      kind: StatefulSet
      name: argocd-application-controller
      version: v1
  - path: ./overlays/argocd-server-deploy-patch.json
    target:
      group: apps
      kind: Deployment
      name: argocd-server
      version: v1

# Each entry in this list should resolve to
# a partial or complete resource definition file.
#
# The names in these (possibly partial) resource files
# must match names already loaded via the `resources`
# field or via `resources` loaded transitively via the
# `bases` entries.  These entries are used to _patch_
# (modify) the known resources.
#
# Small patches that do one thing are best, e.g. modify
# a memory request/limit, change an env var in a
# ConfigMap, etc.  Small patches are easy to review and
# easy to mix together in overlays.
patchesStrategicMerge:
  - ./overlays/argocd-cm.yaml
  - ./overlays/argocd-secret.yaml
